#!/usr/bin/env bash
# check-commit-msg.sh — validate a commit message against ADR-0017.
#
# Usage:
#   scripts/check-commit-msg.sh "feat: add worktree harness"
#   scripts/check-commit-msg.sh path/to/COMMIT_EDITMSG
#
# Accepts either a literal commit message string or a path to a file
# containing one (e.g. for use as a git commit-msg hook).
#
# Validates:
#   - subject line matches Conventional Commits: "type: subject" or
#     "type(scope): subject", with type restricted to the ADR-0017 set
#     (feat fix chore refactor ci docs test perf)
#   - subject is non-empty and non-trivial
#   - message contains no AI-attribution trailer (Co-Authored-By, or
#     "Generated with"/"Generated by" mentioning an AI assistant)
#
# Exit code 0 = accepted, nonzero = rejected (reason printed to stderr).

set -euo pipefail

if [ "$#" -lt 1 ]; then
  echo "usage: $0 <message-string-or-file>" >&2
  exit 2
fi

input="$1"

if [ -f "$input" ]; then
  message="$(cat "$input")"
else
  message="$input"
fi

if [ -z "${message//[[:space:]]/}" ]; then
  echo "REJECTED: commit message is empty" >&2
  exit 1
fi

subject="$(printf '%s\n' "$message" | head -n1)"

allowed_types="feat|fix|chore|refactor|ci|docs|test|perf"

# type: subject   OR   type(scope): subject
pattern="^(${allowed_types})(\([a-zA-Z0-9_./-]+\))?: .+$"

if ! [[ "$subject" =~ $pattern ]]; then
  echo "REJECTED: subject does not match Conventional Commits format." >&2
  echo "  got:      $subject" >&2
  echo "  expected: <type>: <subject> or <type>(<scope>): <subject>" >&2
  echo "  allowed types: feat fix chore refactor ci docs test perf" >&2
  exit 1
fi

# Reject a trivially empty subject body (e.g. "feat: " or "feat:    ")
subject_body="$(printf '%s\n' "$subject" | sed -E "s/^(${allowed_types})(\([a-zA-Z0-9_./-]+\))?: //")"
if [ -z "${subject_body//[[:space:]]/}" ]; then
  echo "REJECTED: subject has no description after the type/scope prefix." >&2
  exit 1
fi

# Reject AI attribution trailers anywhere in the message (per ADR-0017: no
# AI attribution, no Co-Authored-By trailers).
if printf '%s\n' "$message" | grep -Eqi 'co-authored-by|generated (with|by)[[:space:]]+(claude|anthropic|chatgpt|gpt|copilot|gemini|an? ai)'; then
  echo "REJECTED: message contains an AI-attribution trailer (Co-Authored-By / Generated with <AI>), which ADR-0017 forbids." >&2
  exit 1
fi

echo "OK: commit message accepted"
exit 0
