//! Cross-process event types.
//!
//! `DaemonEvent` is the serializable envelope the daemon publishes to every
//! connected client (webui, headless tools). It is the IPC wire contract;
//! adding a variant is a compatibility-relevant change. Kept TUI-free on
//! purpose — nothing in this module may depend on `ratatui` or `crossterm`.

use uuid::Uuid;

use crate::pipeline::{PipelineId, StageId, StageState};
use crate::platform::{ChannelEntry, PlatformKind};
use crate::recording::job::{RecordingJob, RecordingState};

/// Events generated by the daemon (serializable, cross the IPC boundary).
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub enum DaemonEvent {
    ChannelsUpdated(Vec<ChannelEntry>),
    ChannelWentLive(ChannelEntry),
    ChannelWentOffline(ChannelEntry),
    StreamUrlResolved {
        channel_id: String,
        url: String,
    },
    RecordingStarted {
        job: RecordingJob,
    },
    RecordingProgress {
        job_id: Uuid,
        bytes_written: u64,
        duration_secs: f64,
        /// Download percent 0..100 reported by yt-dlp for VOD pulls. None for
        /// live captures (no known total) and for ffmpeg-driven streams.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        download_pct: Option<f32>,
        /// Seconds remaining per yt-dlp's last estimate, or None.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        download_eta_secs: Option<u32>,
        /// Bytes-per-second transfer rate, or None.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        download_rate_bps: Option<u64>,
    },
    RecordingFinished {
        job_id: Uuid,
        final_state: RecordingState,
        error: Option<String>,
    },
    Notification {
        title: String,
        body: String,
    },
    AllRecordingsStopped,
    /// Specific recording rows were removed from `jobs.db` (delete or clear-
    /// errored from the webui). Each subscriber drops these from its own
    /// in-memory recordings map. Distinct from `AllRecordingsStopped` (which
    /// is about lifecycle stops, not deletions).
    RecordingsPruned {
        job_ids: Vec<Uuid>,
    },
    DeviceCodeRequired {
        kind: PlatformKind,
        verification_uri: String,
        user_code: String,
    },
    PlatformAuthenticated {
        kind: PlatformKind,
    },
    PatreonPostFound {
        creator_name: String,
        post_title: String,
    },
    /// Full Patreon snapshot emitted by the monitor on every poll:
    /// pledged creators (as sidebar rows) plus every video-bearing post
    /// per creator. Drives the Patreon section in the sidebar and the
    /// post list in the detail pane (task #69). Replaces the
    /// fire-and-forget PatreonPostFound for UI purposes — that event is
    /// kept only for the status-line ticker.
    PatreonState {
        creators: Vec<ChannelEntry>,
        posts: Vec<crate::platform::patreon::PatreonPost>,
    },
    /// Progress of a per-channel bulk back-catalog download (task #71).
    /// `active` is true while running, false on completion/cancel/error.
    BulkProgress {
        channel_id: String,
        done: usize,
        total: usize,
        active: bool,
    },
    /// Playlists for a YouTube channel, answering ClientMessage::ListPlaylists
    /// to populate the bulk-download scope picker (task #73).
    PlaylistList {
        channel_id: String,
        playlists: Vec<crate::platform::PlaylistInfo>,
    },
    /// A channel's recent VODs (live broadcasts + uploads), answering
    /// ClientMessage::FetchChannelVods for the webui channel-detail pane.
    ChannelVods {
        channel_id: String,
        vods: Vec<crate::platform::VodEntry>,
    },
    /// Result of ClientMessage::ResolveChannel for the Add-Channel wizard
    /// (task #19). `channel_id`/`display_name` are set on success, `error`
    /// on failure.
    ChannelResolved {
        platform: PlatformKind,
        query: String,
        channel_id: Option<String>,
        display_name: Option<String>,
        error: Option<String>,
    },
    /// A cron schedule fired and a recording was kicked off. Includes the
    /// pre-generated `job_id` so the TUI can correlate with the
    /// `RecordingStarted` that follows.
    ScheduleFired {
        channel: String,
        platform: PlatformKind,
        job_id: Uuid,
        duration_secs: u64,
    },
    Error(String),
    /// A pipeline stage transitioned (dispatched/Running, Done, Failed,
    /// Cancelled, Skipped, or reset to Pending for a scheduled retry).
    /// Published by `process_daemon_plugin_actions` and friends
    /// (`src/daemon.rs`) at every DAG-relevant state change so the SPA
    /// can render live pipeline progress (VISION AX-3).
    PipelineStageChanged {
        pipeline_id: PipelineId,
        stage_id: StageId,
        state: StageState,
    },
}
